spring:
  datasource:
    url: jdbc:mysql://localhost:3306/financas_db
    username: root
    password: sua_senha
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: financas-api
server:
  port: 8080
